name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # Node.js setup & cache
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci --legacy-peer-deps

      # Python setup & backend test (pyproject.toml)
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: pip install .
        working-directory: apps/backend
      - run: pytest apps/backend || echo "No backend tests found, skipping."

      # Nx lint/test/build/typecheck
      - run: npx nx run-many -t lint test build typecheck

      # 啟動 frontend/backend 伺服器並執行 e2e 測試
      - run: |
          npx nx serve backend &
          npx nx serve frontend &
          npx wait-on http://localhost:3000 http://localhost:8000
          npx nx run frontend-e2e:e2e || echo "No e2e tests found, skipping."

      # Nx Cloud自動修復CI
      - run: npx nx fix-ci
        if: always()
