name: CD

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for Nx to determine affected projects

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run lint and build for affected projects
        run: npx nx affected -t lint build

      - name: Build Docker images for affected projects
        run: |
          AFFECTED_PROJECTS=$(npx nx show projects --affected)
          for project in $AFFECTED_PROJECTS; do
            docker build -t ${{ secrets.DOCKER_USERNAME }}/$project:latest -f apps/$project/Dockerfile .
          done

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push affected Docker images
        run: |
          AFFECTED_PROJECTS=$(npx nx show projects --affected)
          for project in $AFFECTED_PROJECTS; do
            docker push ${{ secrets.DOCKER_USERNAME }}/$project:latest
          done