name: E2E Tests

on:
  # Run E2E tests on main branch pushes
  push:
    branches:
      - main
  # Run E2E tests nightly
  # schedule:
  #   - cron: '0 2 * * *'  # Every day at 2 AM UTC

  # Allow manual trigger
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual E2E test run'
        required: false
        default: 'Manual E2E test run'

permissions:
  actions: read
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Node.js setup & cache
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci --legacy-peer-deps

      # Python setup for backend
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: pip install .
        working-directory: apps/backend

      # Build frontend
      - name: Build frontend
        run: npx nx build frontend

      # Start services and run E2E tests
      - name: Start backend service
        run: npx nx serve backend &

      - name: Start frontend service
        run: npx nx serve frontend &

      # Wait for services to be ready
      - name: Wait for services
        run: npx wait-on http://localhost:3000 http://localhost:8000 --timeout 120000

      # Run E2E tests
      - name: Run E2E tests
        run: npx nx run frontend-e2e:e2e || echo "No e2e tests found, skipping."

      # Cleanup
      - name: Stop services
        if: always()
        run: |
          pkill -f "nx serve" || true
          pkill -f "uvicorn" || true
          pkill -f "next" || true